# Generated by Django 6.0.1 on 2026-02-25 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subjectteacher',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='subjectteacher',
            name='quizzes_sub_subject_7c69bc_idx',
        ),
        migrations.DeleteModel(
            name='SubjectTeacher',
        ),
    ]
